### ISSUE TITLE
[메인] 스크롤 효과 (이미지 통으로)

### ISSUE THREAD

**Issue by 201steve** [frontend-tech-meeting/twin-programming-Dr.Jart#2]
## subtask without library
- [ ] 오른쪽에 스크롤 인디케이터
- [ ] 스크롤 하면 배너 단위로 딱 맞게 이동
- [ ] 스크롤 하면 문자열 애니메이션 

![scroll](https://user-images.githubusercontent.com/79638133/149274045-4373fed2-7cd4-48de-a547-adbd7b956096.gif)
