### ISSUE TITLE
[Aside] 디자인 유지, 기능을 마켓컬리

### ISSUE THREAD

**Issue by 201steve** [frontend-tech-meeting/twin-programming-Dr.Jart#3]
## subtask without library
- [ ] 상단 + 클릭하면 홈으로 이동, 자동 접힘
- [ ] 메뉴버튼 클릭하면 애니메이션 & 1단 아코디언
- [ ] 마우스 오버하면 1단 아코디언 추가
- [ ] 아코디언 커서 벗어나면 2단은 접힘

![aside](https://user-images.githubusercontent.com/79638133/149276309-420deb73-8f20-439b-885f-778cc6aa4bbe.gif)
